"""
Django settings for pshapes_site project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd*$w((*o16ycr9yuxmdnwimkm&(jikeyp%gp22lg+fhxer&*um'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'pshapes_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pshapes_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


#### CUSTOMIZATIONS ####

INSTALLED_APPS = list(INSTALLED_APPS)

# geo enable
import dj_database_url
DATABASES['default'] =  dj_database_url.config()
DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
if "NAME" not in DATABASES['default']:
    DATABASES['default']["NAME"] = os.path.split(BASE_DIR)[-1]
if "USER" not in DATABASES['default']:
    DATABASES['default']["USER"] = "postgres"
INSTALLED_APPS.append('django.contrib.gis')

# add root template
TEMPLATES[0]['DIRS'].append(os.path.join(BASE_DIR, 'pshapes_site', "templates"))

# add static
STATIC_ROOT = "static"
STATIC_URL = "/static/"
## STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
STATICFILES_STORAGE = "whitenoise.django.GzipManifestStaticFilesStorage"

# add leaflet
INSTALLED_APPS.append('leaflet')
LEAFLET_CONFIG = {
                'SPATIAL_EXTENT': (-180, -90, 180, 90),
                "TILES": [
                        ('osm', 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png', {"noWrap":True}),
                        ('light', 'http://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {"noWrap":True}),
                        ('dark', 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', {"noWrap":True}),
                        ('watercolor', 'http://c.tile.stamen.com/watercolor/{z}/{x}/{y}.png', {"noWrap":True}),
                        ],
                "NO_GLOBALS": False,
                }

INSTALLED_APPS.append('provchanges')
INSTALLED_APPS.append('cshapes')

INSTALLED_APPS.append('rest_framework')
INSTALLED_APPS.append('rest_framework_gis')

REST_FRAMEWORK = {
    # other settings...

    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}


