# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 13:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Alterns', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('ISO', models.CharField(max_length=10)),
                ('FIPS', models.CharField(max_length=10)),
                ('HASC', models.CharField(max_length=10)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
