# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provshapes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provshape',
            old_name='Alterns',
            new_name='alterns',
        ),
        migrations.RenameField(
            model_name='provshape',
            old_name='FIPS',
            new_name='fips',
        ),
        migrations.RenameField(
            model_name='provshape',
            old_name='HASC',
            new_name='hasc',
        ),
        migrations.RenameField(
            model_name='provshape',
            old_name='ISO',
            new_name='iso',
        ),
    ]
