# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provshapes', '0002_auto_20171211_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provshape',
            name='alterns',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='provshape',
            name='fips',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='provshape',
            name='hasc',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='provshape',
            name='iso',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
