# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provshapes', '0004_auto_20171211_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='provshape',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='provshape',
            name='geoj',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='provshape',
            name='geoj_simple',
            field=models.TextField(null=True),
        ),
    ]
