# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provshapes', '0005_auto_20171227_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='provshape',
            name='geoj_simple2',
            field=models.TextField(null=True),
        ),
    ]
