# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provshapes', '0006_provshape_geoj_simple2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provshape',
            name='geoj_simple',
        ),
        migrations.RemoveField(
            model_name='provshape',
            name='geoj_simple2',
        ),
        migrations.AddField(
            model_name='provshape',
            name='simplify',
            field=models.FloatField(null=True),
        ),
    ]
