# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-14 03:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provshapes', '0008_auto_20171228_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CntrShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('simplify', models.FloatField(db_index=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geoj', models.TextField(null=True)),
            ],
        ),
    ]
