# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0009_auto_20161016_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('note', models.IntegerField(null=True)),
                ('added', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('changeid', models.IntegerField(null=True)),
                ('added', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('changeid', models.IntegerField(null=True)),
                ('added', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
            ],
        ),
    ]
