# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0011_note_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='note',
            new_name='changeid',
        ),
        migrations.AddField(
            model_name='comment',
            name='country',
            field=models.CharField(default='NoCountry', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='NoTitle', max_length=100),
            preserve_default=False,
        ),
    ]
