# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0012_auto_20171208_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provchange',
            name='fromtype',
            field=models.CharField(blank=True, choices=[(b'Province', b'Province'), (b'Municipality', b'Municipality'), (b'District', b'District'), (b'County', b'County'), (b'State', b'State'), (b'Parish', b'Parish'), (b'Region', b'Region'), (b'Prefecture', b'Prefecture'), (b'Department', b'Department'), (b'Governate', b'Governate'), (b'Territory', b'Territory'), (b'Commune', b'Commune'), (b'Circumscription', b'Circumscription'), (b'Other...', b'Other...')], max_length=40, verbose_name='From province type'),
        ),
    ]
