# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0014_auto_20171222_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('added', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(null=True)),
                ('note', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000, null=True)),
                ('wms', models.URLField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('added', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('citation', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000, null=True)),
                ('is_resource', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provchanges.Source'),
        ),
        migrations.AddField(
            model_name='provchange',
            name='mapsources',
            field=models.ManyToManyField(related_name='mapsources_set', to='provchanges.Map', verbose_name='Maps used for information'),
        ),
        migrations.AddField(
            model_name='provchange',
            name='sources',
            field=models.ManyToManyField(to='provchanges.Source', verbose_name='Sources of information'),
        ),
        migrations.AddField(
            model_name='provchange',
            name='transfer_map',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_map_set', to='provchanges.Map', verbose_name='Map used to draw geometry'),
        ),
    ]
