# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0016_auto_20180103_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='country',
            field=models.TextField(blank=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='map',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='provchanges.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.TextField(blank=True, verbose_name='Country'),
        ),
    ]
