# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0017_auto_20180107_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provchanges.Source'),
        ),
    ]
