# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0018_auto_20180107_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provchange',
            name='type',
            field=models.CharField(choices=[(b'NewInfo', b'NewInfo'), (b'PartTransfer', b'PartTransfer'), (b'FullTransfer', b'FullTransfer'), (b'Breakaway', b'Breakaway'), (b'Begin', b'Begin')], max_length=40, verbose_name='Type of Change'),
        ),
    ]
