# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0019_auto_20180107_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='institution',
            new_name='affiliation',
        ),
    ]
