# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0020_auto_20180111_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provchange',
            name='fromtype',
            field=models.CharField(blank=True, choices=[(b'Province', b'Province'), (b'Municipality', b'Municipality'), (b'District', b'District'), (b'County', b'County'), (b'State', b'State'), (b'Parish', b'Parish'), (b'Region', b'Region'), (b'Prefecture', b'Prefecture'), (b'Department', b'Department'), (b'Governate', b'Governate'), (b'Territory', b'Territory'), (b'Commune', b'Commune'), (b'Circumscription', b'Circumscription'), (b'Cercle', b'Cercle'), (b'Division', b'Division'), (b'Other...', b'Other...')], max_length=40, verbose_name='From province type'),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='totype',
            field=models.CharField(blank=True, choices=[(b'Province', b'Province'), (b'Municipality', b'Municipality'), (b'District', b'District'), (b'County', b'County'), (b'State', b'State'), (b'Parish', b'Parish'), (b'Region', b'Region'), (b'Prefecture', b'Prefecture'), (b'Department', b'Department'), (b'Governate', b'Governate'), (b'Territory', b'Territory'), (b'Commune', b'Commune'), (b'Circumscription', b'Circumscription'), (b'Cercle', b'Cercle'), (b'Division', b'Division'), (b'Other...', b'Other...')], max_length=40, verbose_name='To province type'),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=400, verbose_name='Map description'),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='transfer_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to map data'),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='type',
            field=models.CharField(choices=[(b'NewInfo', b'NewInfo'), (b'MergeNew', b'MergeNew'), (b'TransferNew', b'TransferNew'), (b'MergeExisting', b'MergeExisting'), (b'TransferExisting', b'TransferExisting'), (b'Breakaway', b'Breakaway'), (b'SplitPart', b'SplitPart'), (b'PartTransfer', b'PartTransfer'), (b'FullTransfer', b'FullTransfer'), (b'Begin', b'Begin')], max_length=40, verbose_name='Type of Change'),
        ),
    ]
