# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0021_auto_20180121_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('changeid', models.IntegerField(null=True)),
                ('added', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Resolved', b'Resolved'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('added', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('text', models.CharField(max_length=2000)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provchanges.Issue')),
            ],
        ),
    ]
