# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0022_issue_issuecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='source',
            field=models.CharField(max_length=10000, verbose_name='Source of information'),
        ),
    ]
