# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 09:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0023_auto_20180506_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='provchange',
            name='fromcapitalmove',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='From province capital (moved)'),
        ),
        migrations.AddField(
            model_name='provchange',
            name='tocapitalmove',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='To province capital (moved)'),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='fromtype',
            field=models.CharField(blank=True, choices=[(b'Province', b'Province'), (b'Municipality', b'Municipality'), (b'District', b'District'), (b'County', b'County'), (b'State', b'State'), (b'Parish', b'Parish'), (b'Region', b'Region'), (b'Prefecture', b'Prefecture'), (b'Department', b'Department'), (b'Governate', b'Governate'), (b'Territory', b'Territory'), (b'Commune', b'Commune'), (b'Circumscription', b'Circumscription'), (b'Cercle', b'Cercle'), (b'Division', b'Division'), (b'Fiefdom', b'Fiefdom'), (b'Other...', b'Other...')], max_length=40, verbose_name='From province type'),
        ),
        migrations.AlterField(
            model_name='provchange',
            name='totype',
            field=models.CharField(blank=True, choices=[(b'Province', b'Province'), (b'Municipality', b'Municipality'), (b'District', b'District'), (b'County', b'County'), (b'State', b'State'), (b'Parish', b'Parish'), (b'Region', b'Region'), (b'Prefecture', b'Prefecture'), (b'Department', b'Department'), (b'Governate', b'Governate'), (b'Territory', b'Territory'), (b'Commune', b'Commune'), (b'Circumscription', b'Circumscription'), (b'Cercle', b'Cercle'), (b'Division', b'Division'), (b'Fiefdom', b'Fiefdom'), (b'Other...', b'Other...')], max_length=40, verbose_name='To province type'),
        ),
    ]
