# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0025_auto_20180602_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Active', b'Active'), (b'Completed', b'Completed'), (b'Withdrawn', b'Withdrawn')], default=b'Active', max_length=40)),
                ('added', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('model', models.CharField(choices=[(b'ProvChange', b'ProvChange'), (b'Map', b'Map'), (b'Issue', b'Issue')], max_length=40)),
                ('subset', models.TextField(blank=True)),
                ('condition', models.TextField(blank=True)),
            ],
        ),
    ]
