# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provchanges', '0026_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='model',
            field=models.CharField(choices=[(b'ProvChange', b'ProvChange'), (b'Map', b'Map'), (b'Source', b'Source'), (b'Issue', b'Issue')], max_length=40),
        ),
    ]
